name: naver-geocode-proxy
app: node@16
options:
  env:
    - name: NODE_ENV
      value: production
    - name: NCP_CLIENT_ID
      value: ${{ secrets.NCP_CLIENT_ID }}
    - name: NCP_CLIENT_SECRET
      value: ${{ secrets.NCP_CLIENT_SECRET }}
  ports: 3000
  install: npm install
  start: npm start
  buildenv: []
context:
  git:
    url: https://github.com/page1762/naver-geocode-proxy.git
    branch: main
  preset: node
