name: naver-geocode-proxy
app: node@16
options:
  install: npm install
  start: npm start
  env:
    - name: NCP_CLIENT_ID
        value: ${{ secrets.NCP_CLIENT_ID }}
      - name: NCP_CLIENT_SECRET
        value: ${{ secrets.NCP_CLIENT_SECRET }}
  buildenv: []
context:
  git:
    url: https://github.com/page1762/naver-geocode-proxy.git
