name: Deploy to cloudtype
on:
  push:
    branches:
      - main
  schedule:
    - cron: '50 0 * * *'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: page1762/naver-geocode-proxy
          stage: main
          yaml: |
            name: naver-geocode-proxy
            app: node@16
            options:
              env:
                - name: NODE_ENV
                  value: production
                - name: NCP_CLIENT_ID
                  value: ${{ secrets.NCP_CLIENT_ID }}
                - name: NCP_CLIENT_SECRET
                  value: ${{ secrets.NCP_CLIENT_SECRET }}
              ports: 3000
              install: npm install
              start: npm start
              buildenv: []
            context:
              git:
                url: https://github.com/page1762/naver-geocode-proxy.git
                ref: ${{ github.ref }}
              preset: node
