name: Deploy to cloudtype

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 22 * * *'  # 매일 오전 7시(KST) 실행
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: page1762/naver-geocode-proxy
          stage: main
          yaml: |
            name: naver-geocode-proxy
            app: naver-geocode-proxy

            options:
              env: []
              buildenv: []

            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}

            services:
              - name: web
                type: web
                build:
                  base: node@18
                  install: npm install
                run:
                  command: npm start
                env:
                  - name: NODE_ENV
                    value: production
                  - name: NCP_CLIENT_ID
                    value: tpog4appfl
                  - name: NCP_CLIENT_SECRET
                    value: H4cqm0QCyyshRvXjRHhorahyl5hYDe1S32XSQLRm
                ports:
                  - 3000
                root: .
