name: Deploy to cloudtype

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: page1762/naver-geocode-proxy
          stage: main
          file: .cloudtype/app.yaml
