name: Trigger Cloudtype Deploy via Minimal Code Change

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: master  # 혹은 저장소 기본 브랜치명 (main인지 master인지 확인 후 수정)

      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Make minimal change to README.md and push
        run: |
          FILE="README.md"
          if [ ! -f $FILE ]; then
            echo "# Temp README for redeploy" > $FILE
          fi

          echo "# redeploy triggered at $(date)" >> $FILE

          git add $FILE
          git commit -m "Trigger redeploy: update README.md $(date)" || echo "No changes to commit"
          git push origin HEAD  # HEAD 기준으로 푸시
