name: Trigger Cloudtype Deploy via API

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 매일 0시 UTC 실행

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deploy via Cloudtype API
        env:
          CLOUDTYPE_API_TOKEN: ${{ secrets.CLOUDTYPE_API_TOKEN }}
        run: |
          curl -X POST "https://api.cloudtype.io/api/v1/projects/page1762/naver-geocode-proxy/deploy" \
            -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJtY2UzcHRtOWI4ZWUyOTllIiwiaWF0IjoxNzUyMDI0MDI4fQ.QChMxwWmMuecOVc-4bJUJfiUMHaMz2jCBVLq3cpOVRQ"
