name: Trigger Cloudtype Deploy via Webhook

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Cloudtype via webhook
        env:
          WEBHOOK_SECRET: ${{ secrets.CLOUDTYPE_WEBHOOK_SECRET }}
        run: |
          curl -X POST https://api.cloudtype.io/webhooks/deploy \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $WEBHOOK_SECRET" \
            -d '{
              "project": "page1762",
              "app": "naver-geocode-proxy",
              "stage": "main"
            }'
