name: Trigger Cloudtype Deploy via Git Push

on:
  workflow_dispatch:  # 수동 실행
  schedule:
    - cron: '0 0 * * *'  # 매일 자정 (UTC) → 한국 오전 9시

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Dummy commit to trigger Cloudtype
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          echo "// redeploy: $(date)" >> .deploy-log.txt
          git add .deploy-log.txt
          git commit -m "Trigger redeploy at $(date)" || echo "Nothing to commit"
          git push
