name: Trigger Cloudtype Deploy via Dummy File Change

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 매일 0시 UTC

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Update dummy deploy trigger file and push
        run: |
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "Redeploy triggered at $(date)" > .dummy-deploy-trigger
          git add .dummy-deploy-trigger

          # 커밋할 변경사항이 있으면 커밋하고 푸시
          git diff-index --quiet HEAD || (
            git commit -m "Trigger redeploy at $(date)"
            git push origin "$BRANCH"
          )
