name: Trigger Cloudtype Deploy via Minimal Code Change

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 매일 0시 UTC에 실행

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # 기본 브랜치 자동 감지용으로 ref 생략 가능 (기본 브랜치 자동 체크아웃)
          # 만약 기본 브랜치가 명확하면 ref: main 또는 master 로 명시 가능

      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Make minimal change to README.md and push
        run: |
          FILE="README.md"
          if [ ! -f "$FILE" ]; then
            echo "# Temp README for redeploy" > "$FILE"
          fi

          echo "# redeploy triggered at $(date)" >> "$FILE"

          git add "$FILE"

          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "Current branch is $BRANCH"

          # 변경사항 있으면 커밋 + 푸시
          git diff-index --quiet HEAD || (
            git commit -m "Trigger redeploy: update README.md $(date)"
            git push origin "$BRANCH"
          )
