name: Trigger Cloudtype Deploy via Tag Push

on:
  workflow_dispatch:    # 수동 실행 가능
  schedule:
    - cron: '0 0 * * *'  # 매일 0시 UTC(한국시간 9시)에 자동 실행

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Create and push deploy tag
        run: |
          TAG="deploy-$(date +'%Y%m%d%H%M%S')"
          echo "Creating tag $TAG and pushing to origin"
          git tag $TAG
          git push origin $TAG
